title: Giorgia Zaccaria
theme: Minima

author: Giorgia Zaccaria
  name: giorgiazaccaria
  email: giorgia.zaccaria@unitelmasapienza.it
description: > # this means to ignore newlines until "show_excerpts:"
 Hi, thank you for visiting my webpage! If you are interested in my research, please feel free to contact me.
 
- about.md
