title: Giorgia Zaccaria

author:
  name: GitHub User
  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Thank you for visiting my webpage! If you are interested in my research, please feel free to contact me at [giorgia.zaccaria@unitelmasapienza.it](https://mailto:giorgia.zaccaria@unitelmasapienza.it)

 social_links:
    twitter: jekyllrb
    github:  jekyll
    
theme: Minima



