title: Giorgia Zaccaria

author: Research Fellow, University of Rome Unitelma Sapienza
description: > # this means to ignore newlines until "show_excerpts:"
  Thank you for visiting my webpage! 
  If you are interested in my research, please feel free to contact me at <a href="mailto:giorgia.zaccaria@unitelmasapienza.it" target="_blank">giorgia.zaccaria@unitelmasapienza.it</a>.
    
theme: Minima



